### ISSUE TITLE
Error 404 The requested page does not exist when creating host

### ISSUE THREAD

**Issue by grektum** [echothrust/echofish#14]
I get this error on creation of a new host.

host is created ok though with a different from the specified one.

**Comment by proditis** [comment]
Hi,

Have you downloaded the release v0.4 archive? If so can you try to download the master (https://github.com/echothrust/echofish/archive/master.tar.gz) and see if this fixes the problems for you (wrong redirect & host creation) ? 

Regards,

Pantelis
