### ISSUE TITLE
mysqld floods log with warnings after starting echofish

### ISSUE THREAD

**Issue by grektum** [echothrust/echofish#15]
I just installed echofish following instructions in the INSTALL.md file (skipped the mail configuration as this is not needed for now) and upon starting it, mariadb started flooding logs with warnings.

```
mysqld: 150104  0:22:03 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. Statement is unsafe because it invokes a trigger or a stored function that inserts into an AUTO_INCREMENT column. Inserted values cannot be logged correctly. Statement: INSERT INTO archive_bh (host, facility, priority, level, received_ts, program, msg,pid,tag) VALUES ( '127.0.0.1', '5', '6','6', '20150104002203', TRIM('rsyslogd'), TRIM(' [origin software="rsyslogd" swVersion="8.6.0" x-pid="8021" x-info="http://www.rsyslog.com"] start'),'', 'rsyslogd:' )
```

```
mysqld: 150104  0:22:03 [Note] Suppressing warnings of type 'Statement is unsafe because it uses a system function that may return a different value on the slave.' for up to 300 seconds because of flooding
mysqld: 150104  0:22:03 [Note] Suppressing warnings of type 'Statement accesses nontransactional table as well as transactional or temporary table, and writes to any of them.' for up to 300 seconds because of flooding
mysqld: 150104  0:22:03 [Note] Suppressing warnings of type 'Statements writing to a table with an auto-increment column after selecting from another table are unsafe because the order in which rows are retrieved determines what (if any) rows will be written. This order cannot be predicted and may differ on master and the slave.' for up to 300 seconds because of flooding
```

**Comment by proditis** [comment]
Hi there,

Do you have replication configured for this database? 

It seems that the `binlog_format` is set to `statement`, (is the default now on MariaDB). If you dont have replication configured you can try to change the variable to `mixed` and see if that eliminates the warnings.

Test it out by executing
```
mysql> SET GLOBAL binlog_format = 'MIXED';
```
and if that eliminates the error you can make it permanent by opening ```my.cnf``` (usually ```/etc/my.cnf``` or ```/etc/mysql/my.cnf```) and changing the following setting to read

```
...
[mysqld]
...
binlog_format=mixed
...
```

Let us know how this one goes.

Regards,

Pantelis

**Comment by grektum** [comment]
Thanks for the answer.

We don't have replication as this is a test server we use to give a try to different solutions.

Sorry I can"t try the proposed fix as i removed the whole installation to set up logstash instead, but from what I've gathered it seems switching to mixed instead of statement would fix the issue.
