### ISSUE TITLE
Abuser not working?

### ISSUE THREAD

**Issue by ohmer1** [echothrust/echofish#19]
I'm trying to create triggers for the abusers module.  Doesn't seem to work.  Don't know if I do something wrong.

Example string I'm trying to catch:
`Failed password for xxxxx from a.b.c.d port 12345 ssh2`

Msg:
`Failed password for % from %`

Pattern:
`/from (.*?) port.*/`

All others fields, I used default value.

Abusers are not reported in the incidents tab.

**Comment by gadamo** [comment]
Hi ohmer1,

Just a few quick thoughts on this issue:

1) Make sure that mysql event scheduler is ```ON```, 

2) About your pattern, with a first look it could be a matter of escaping the spaces (/from\ (.*?)\ port.*/), but i can't test right now (on the move).

3) Perhaps, I would try the following:

Msg: ```Failed password for % from % ssh2```
Pattern: ```/(([0-9]+)(?:\.[0-9]+){3})/```
Grouping: ```1```
Capture: ```1```

Notice the msg is matched more carefully, to be certain that the simple pattern that follows will only apply to relevant msgs. Also this pattern is more specific for ip address.

Please let me know how this worked for you. It's holiday now in Greece, but i'll try to respond whenever it's possible.

Thank you for the report,
George

**Comment by ohmer1** [comment]
> 1) Make sure that mysql event scheduler is ON, 
I have `event_scheduler=on` in the mysqld section of `/etc/mysql/my.cnf`

> 2) About your pattern, with a first look it could be a matter of escaping the spaces (/from\ (.?)\ port./), but i can't test right now (on the move).
> 
> 3) Perhaps, I would try the following:

It doesn't work.

This can wait tomorrow ;)  Have a nice day!

**Comment by gadamo** [comment]
Hi,

To verify this case, connect to the mysql service with mysql client and run:

```
mysql> SELECT @@EVENT_SCHEDULER;
```

This should already be ON, check just to be safe. Then connect to Echofish database (replace name with yours) and run:

```
mysql> use ETS_echofish;
mysql> SHOW EVENTS;
```

The Status for all events should appear ENABLED. My focus is on the archive event ```e_archive_parse_unparsed``` that stays disabled when there is an error. As part of its operation the event disables its self upon start, processes the unparsed archive entries and re-enables it self back.

Also check the mysql error log (```show variables like 'log_error';```) and let us know of your results. I am sure we will troubleshoot it eventually.

Sorry for the delay in replying,

George

**Comment by gadamo** [comment]
Note: as explained in the previous comment, the event ```e_archive_parse_unparsed``` disables itself (to avoid concurrent runs by the event scheduler) and re-enables itself at the finish of a successful run. If the  event shows up DISABLED, please run ```show events;``` again a couple of times to make sure that it stays DISABLED.

If the event stays DISABLED, you will also have entries building up in the ```archive_unparse``` table as a side-effect (running ```select count(*) from archive_unparse;``` will show a large number).

Kind regards,
George

**Comment by ohmer1** [comment]
Hello,

I just have the e_populate_whitelist_mem event.  There is no e_archive_parse_unparsed.

I opened echofish-events.sql and I see there is a CREATE EVENT e_archive_parse_unparsed.  I tried to recreate manually the event.

> CREATE EVENT e_archive_parse_unparsed
> ON SCHEDULE EVERY 10 SECOND COMMENT 'PROCESS ' DO
> BEGIN
>   ALTER EVENT e_archive_parse_unparsed DISABLE;
>   call archive_parse_unparsed();
>   SELECT id into @local_id_avoid_mysql_bug FROM `user` limit 1;
>   ALTER EVENT e_archive_parse_unparsed ENABLE;
> END

But I get:
> #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4 

I'm running mysqld 5.5.41-0ubuntu0.14.04.1 .

**Comment by gadamo** [comment]
Hi there,

Just to make sure, import all of the following - not just echofish-events.sql (this will not affect your data, it's only program logic):

```
mysql ETS_echofish < schema/echofish-functions.sql
mysql ETS_echofish < schema/echofish-procedures.sql
mysql ETS_echofish < schema/echofish-triggers.sql
mysql ETS_echofish < schema/echofish-events.sql
```

These commands should give no errors, please report otherwise. 

Now you can check again with ```show events;``` if the event ```e_archive_parse_unparsed``` is there and enabled.

Note: Some versions/builds of mysql seem to drop disabled events when the service is restarted. A bad regex in abusers can leave the event permanently disabled. This, followed by a restart of the service may cause the event to be dropped.

**Comment by ohmer1** [comment]
I executed again sql files to create the required structure.  The table archive_unparse had over 800k records and this dropped slowly to 0.  The abuser reporting seem to work now.

**Comment by gadamo** [comment]
I am glad this worked out for you, but we never confirmed how this problem emerged in the first place.

Which procedure did you follow for the initial setup? I went through the steps on all the guides (the generric ```INSTALL.md``` and the guides in ```/contrib```) and we don't seem to miss a step there.

Do you recall a mysql service restart during your troubleshooting? If yes, would you be willing to attempt reproducing the bug? My idea is to try your initial regex pattern ```/from (.*?) port.*/``` and see what happens to the events (```show events;```):
* does it cause the ```e_archive_parse_unparsed``` to get disabled indeed?
* does a subsequent restart of the mysql service cause the disabled event to be dropped?

Thank you for your time,
George

**Comment by ohmer1** [comment]
I'm sure at 99% that I executed all the commands listed in INSTALL.md.  I may have restarted mysql too.

I edited my trigger and put the old regexp and this disabled the event.  After a restart of mysqld, the event was gone.

**Comment by gadamo** [comment]
Hi ohmer1,

We have come up with some ideas to combat with this issue (e.g. add code to check regexp is valid before applying it). 

So I am leaving this issue open until we have something in place that mitigates the problem.

Thank you for the bug report,

George

**Comment by gadamo** [comment]
@ohmer1 Closing this issue. Past year's development has reworked the REGEXP part; Echofish is no longer dependent on external UDF for this, and requires MariaDB that natively includes REGEXP functions. An invalid pattern should no longer be an issue.
