### ISSUE TITLE
Manage Host

### ISSUE THREAD

**Issue by geckeon** [echothrust/echofish#22]
Hello,
I use a rsyslog server and i have multiple source log.
Manege Host don't work correctly for me.
Resolve Host do nothing.
When a new log server comes up, in the manage host i have 0.0.0.0 value for ipoctet.
Host Ip in Syslog Tabs use ipoctet values.
If i would modify ipoctet with 192.168.0.100 it's impossible because limited to 10 char.
I change the lenght field to 16 in database and php files.
I wish change triggers in archive_bh table for new host to write in ip.host table but it's an int value and they have a problem with IP format. 

Geckeon.

**Comment by proditis** [comment]
Hi there,

Have you downloaded the v0.4.1 release? If so can you please try the master branch instead? 

Hopefully this will solve all the issues you've been having, if not let us know .

**Comment by geckeon** [comment]
I use the last release " wget https://github.com/echothrust/echofish/archive/master.zip".

**Comment by gadamo** [comment]
Hosts should be auto-generated. You shouldn't need to manually create hosts, although it seems you stumbled into a bug with the field's limit on the form.

Please provide your rsyslog configuration, especially the template lines used to insert logs to mysql. It should resemble the config in https://github.com/echothrust/echofish/blob/master/contrib/rsyslog-echofish.conf

**Comment by geckeon** [comment]
I find where is my problem for new host, i modify :
echofish/schema/echofish-triggers.sql -- line 26 -- ip to int
INSERT INTO `host` (ip,fqdn,short) values (inet_aton(NEW.host),NEW.host,NEW.host);

echofish/schema/00_echofish-schema.sql -- line 383 -- ip adress max lenght 255.255.255.255
ip int(16) unsigned default 0,

echofish/htdocs/protected/modules/settings/views/host/_form.php -- line 9 ip adress max lenght
<?php echo $form->textFieldRow($model,'ip',array('class'=>'span5','maxlength'=>16)); ?>

echofish/htdocs/protected/modules/settings/views/host/_search.php -- line 8 ip adress max lenght
<?php echo $form->textFieldRow($model,'ip',array('class'=>'span5','maxlength'=>16)); ?>

But i always have a problem to resolve DNS.

**Comment by proditis** [comment]
Hi there, great detective work (helped a lot, thanks). 
Please revert back all the schema changes. Change the `maxlength` to `16` on the 2 php files (`settings/views/host/_search.php` and `settings/views/host/_form.php`) and try to modify/add a host. Once this is working we can proceed in solving what is wrong with the DNS.

**Comment by geckeon** [comment]
Hi,
I have modify php and database before my post, and i try to add/modify a host without problem, automatically adding new host works fine too ^^.
But i always have a problem to Resolve Host in Manage Host, it isn't a big issue but don't work for me.
I don't know where is the code to help you.
Geckeon.

**Comment by proditis** [comment]
Great news :+1: 

Lets fix the resolve problem now. 

Can you provide some more information about your web server and php setup? 
 * Operating system and version
 * Do you run apache, nginx or something else? 
 * Do you run your php through fpm, cgi or mod_php? 
 * Do you use `chroot` for your setup?

The resolve operation uses the standard PHP function `gethostbyaddr()` which usually fails on chrooted environments if the required resolver configuration files are not there (eg resolv.conf).

Once we have these details we will be able to figure out why you cant resolve.

PS: The code for the resolve operation is located under `protected/models/Host.php` line 134.

**Comment by geckeon** [comment]
I use debian jessie 8.1, apache 2.4.10, php_fpm, i don't use chroot.

**Comment by proditis** [comment]
Can you try running this script https://gist.github.com/proditis/605ab696d863441d625b and provide the output produced?

This script can also be run from the command line, it checks that forward and reverse dns lookups work on a system.
```
php ./check_dns.php google.com 8.8.8.8
```
or
```
http://localhost/check_dns.php?domain=google.com&inaddr=8.8.8.8
```

**Comment by geckeon** [comment]
I have make some test, the DNS resolution work on page "Update Host" and use the fonction "resolve" in protected/models/Host.php but on the Manage Host page i think the fonction is resolve_all and i think it doesn't exist (protected/modules/settings/views/host/admin.php line 10).

**Comment by geckeon** [comment]
I have modify resolve fonction, protected/models/Host.php on line 137 by
if($this->fqdn!==$this->ipoctet)
Because gethostbyaddr return IP adress if error ocurs.

**Comment by proditis** [comment]
Thanks for catching this one. we changed it into this (will commit shortly)
```
if($this->fqdn!==false && $this->fqdn!==$this->ipoctet)
```

However, the resolve_all is a controller action (`protected/modules/settings/controllers/HostController.php`) that simply wraps `host->resolve()`. 

What error do you get when you try to resolve_all ?

**Comment by geckeon** [comment]
I don't know why but now all works :)

**Comment by proditis** [comment]
That's good (but strange).

Keep an eye if it happens again so that we can track it down. 

We'd like to thank you for taking the time to investigate the problem and provide us with valuable feedback.

We'll be closing this issue for now since it "seems" to be resolved. If you experience any other issues with Echofish don't hesitate to open a new issue.

Pantelis

**Comment by proditis** [comment]
Hi there again,

I think we found the problem with resolve hosts (and why it appeared to be fixed auto-magically). 

The problem was in the logic of `resolve()`, it didn't take into consideration the fact that we no longer have IP as primary source of information for the host.  

Re-opening the issue for now, we will commit an update shortly.

Sorry for the trouble.

**Comment by proditis** [comment]
The following files have been updated with regards to the DNS resolve issue,
* `htdocs/protected/models/Host.php`
* `htdocs/protected/modules/settings/views/host/_form.php`

Can you please give them a try? Make sure you reverse your SQL changes back to the original.

**Comment by tconstans** [comment]
Hello,

I just installed newest version of echofish with remote logging via rsyslog.

In main window, Hot IP is 0.0.0.0 and in settings/host show:
  - ipoctet 0.0.0.0
  - fqdn : ip of server
  - shortname : ip of server
  - description : null
I have just git pulled latest changes (the one mentionned in previous message)

Best regards

**Comment by proditis** [comment]
Hi there Thomas,  long time no see.

Can you perform the steps outlined in UPGRADE.md and try again? If you still experience problems please open a separate issue (to avoid confusion with this one)

PS: We're really glad you're ok. Its not the place for this, but in these difficult times for France, our hearts are with you.

**Comment by tconstans** [comment]
Hello Proditis, thanks for your support.

It is a fresh install, not an upgrade

**Comment by proditis** [comment]
It still requires the upgrade steps. This was done in order to avoid breaking existing installations.

**Comment by geckeon** [comment]
Hi,
You can test to modify schma/echofish-trigger.sql in line 26 with 
INSERT INTO `host` (ip,fqdn) values (INET_ATON(NEW.host),NEW.host);

**Comment by proditis** [comment]
@geckeon you're right, sorry for taking so long to realize what you were suggesting :)

Changed line 26 of schema/echofish-triggers.sql into
```
INSERT INTO `host` (`ip`,`fqdn`,`short`) values (INET_ATON(NEW.host),NEW.host,NEW.host);
```

Just committed the change.

**Comment by geckeon** [comment]
Thx :)

**Comment by tconstans** [comment]
Dear all,
I confirm the following:
  - modifying trigger fix my issue.
  - auto host resolution works

Thanks again for the quick feedback and solution !

**Comment by proditis** [comment]
So can we finally close this cursed issue? :)

**Comment by geckeon** [comment]
It's ok for me with the last mofication ^^

**Comment by tconstans** [comment]
ok for me

**Comment by proditis** [comment]
goodbye issue 22
