### ISSUE TITLE
Archive desactivated

### ISSUE THREAD

**Issue by geckeon** [echothrust/echofish#24]
When archive is desactivate in Sysconfig, the Whitelist don't work.
All log are send to syslog table.
And when i acknowledge a log, this last is drop. It's possible to pull them in archive table.

Best Regards.

**Comment by proditis** [comment]
Hi geckeon,

I'll investigate the problem with whitelists and get back to you.

As for the "acknowledge" operation, just to be sure i understand what you need, you want the entries that get "acknowledged" instead to go to the "archive"?

**Comment by geckeon** [comment]
For the "acknowledge" operation, i would like that this entries go to "archive".
Actuality this entries are lost.

**Comment by proditis** [comment]
Can you give a try and re-import the `schema/echofish-triggers.sql` and see if this solved the problem with the whitelists?

As for the "Acknowledge to Archive" sound like a good idea, can you open a new issue so that we can address it separately (since its a feature request)?

**Comment by geckeon** [comment]
Problem solved with your modification. Good Job :)
I will open a new issue for "Acknowledge to Archive"
Geckeon.

**Comment by proditis** [comment]
Great :+1: 

Closing this one and waiting for the new issue :)

Pantelis
