### ISSUE TITLE
Acknowledge to Archive

### ISSUE THREAD

**Issue by gadamo** [echothrust/echofish#25]
As proposed by @geckeon on issue #24 it makes sense, when archive is disabled, that acknowledged logs will be moved to the archive. Perhaps introducing a configuration flag.

**Comment by proditis** [comment]
In order to test please follow these steps (order is important)
* Create a sysconfig entry `whitelist_archived` with value `yes`. 
* Import `schema/echofish-triggers.sql`
* Go back to sysconfig and make sure `archive_enabled` is set to `no`.
* Acknowledge a syslog entry
* Verify that entry/entries are on archive

**Comment by geckeon** [comment]
For me the proper functioning is : when new log come in archive_bh if archive_enable=yes and whitelist.patern find go to archive elseif archive_enable=no and whitelist.patern find drop log else whitelist.patern not find go to syslog (with this behavior that avoid duplication entries between syslog and archive)
In syslog page when they are an acknowledge and if archive_enable=yes move to archive else drop entry.

**Comment by gadamo** [comment]
Until now, with `archive_enable=yes`, it is made sure that *everything* is logged to the archive. This way `archive` provides a full view of all events at all times, while `syslog` provides a separate dataset of filtered logs that the user can acknowledge/purge without losing their archived duplicates.

With the recent changes, when `archive_enable=no`, messages that are acknoledged on the `syslog` view will not be purged, but should now be "moved" to the archive.

@geckeon I believe it is exactly what you describe, right? You can try the latest changes by @proditis

**Comment by geckeon** [comment]
@gadamo, it's not exactly what I said but it's what i want ;)
Good jobs :+1:

**Comment by gadamo** [comment]
If you repeated the steps outlined by @proditis in the first comment, please keep an eye in mysql.err file for the next couple of days (we will also keep an eye on our test env) to make sure we don't hit any deadlocks or other edge cases.

If we don't receive any negative feedback, this issue will be close within this week.

Thanks for your feedback,

**Comment by gadamo** [comment]
@proditis Initial feedback is that the sysconfig key should be renamed from `whitelist_archived` to `archive_acked` or similar.
