### ISSUE TITLE
Mass Ack Bug

### ISSUE THREAD

**Issue by geckeon** [echothrust/echofish#28]
Hello,
I think i found a bug, when i search Host IP in Syslog/Logs page and i wants to use massack nothing append. All other research Facility, Level, Program and Msg works with massack.
A question, is it possible to display short name for host ip to have is name when it use resolve host.

Geckeon.

**Comment by gadamo** [comment]
This appears to be a framework bug, but @proditis worked around it in the latest commit.

Please try the latest changes in htdocs/protected/modules/syslog/models/Syslog.php

**Comment by geckeon** [comment]
I use the latest changes and now mass ack work.
Good.

**Comment by gadamo** [comment]
It seems the bug was not completely fixed afterall.

With the changes introduced in current master, massack does not work when all filters are empty (i.e. when trying to mass-acknowledge everything in syslog table). 

The response got from developer tools is Error 500 (Internal Server Error):

```
CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version
 for the right syntax to use near '' at line 1
```

**Comment by geckeon** [comment]
Indeed massack does not work when all filters are empty but I don't have an error 500, forme nothing happens.
It's possible to add a checkbox in all log line to use Mass Acknowledge Selected button in the bottom page.

**Comment by gadamo** [comment]
The latest code merge from @proditis should fix this issue. 

Please pull the latest changes and test in your setup to provide feedback.

Thank you.

**Comment by geckeon** [comment]
That works for me too :)
