### ISSUE TITLE
documentation needed

### ISSUE THREAD

**Issue by tconstans** [echothrust/echofish#34]
Dear all,

I just noticed the following settings:

archive_activated	yes	
archive_delete_days	7	
archive_delete_limit	0	
archive_delete_use_mem	no	
archive_rotate	yes	
whitelist_archived	no

I have already played with the first. I have some clues about the second, but the other requires some clarifications.

Best regards

**Comment by gadamo** [comment]
Yes, new toys require proper wrapping :)

Collecting the material from the relevant commits that introduced the new configuration keys:

1. #25 https://github.com/echothrust/echofish/commit/c7ac0fd5e8259b302b9b7dea4e2e3775d49f332d
   * whitelist_archived: (default:'no') Whitelisted syslog entries are archived, requires that archive_activated is set to 'no'
2. #23 https://github.com/echothrust/echofish/commit/87ca75098cf5445131fdaf565fe13183528d1b52
   * archive_rotate: (default:'yes') Trim entries older than than `archive_delete_days` days
   * archive_delete_use_mem (default:'no') Use ENGINE=memory for intermediate temporary table that is created during rotation
   * archive_delete_days (default:7) How many days of archive logs to keep. Older entries will be trimmed from the archive table during rotation
   * archive_delete_limit (default:0) Setting a value here will set a maximum limit on the number of entries than can be trimmed during rotation


Hope this helps,

**Comment by ardichoke** [comment]
Along the same vein, it would also be useful to have documentation about what is valid whitelist syntax. I tried writing some PCRE statements to filter out messages (which I validated with various PCRE validators) but none of them seemed to work. I'm still unclear about what is and isnt' a valid pattern and I haven't found anything in the documentation to explain it.

**Comment by proditis** [comment]
Hi there @ardichoke,

thanks for your feedback. Sorry to hear you had troubles with the whitelist syntax. Did you check the Whitelist help section out (/echofish/index.php?r=lists/default/help)? The whitelist pattern follows the `LIKE` syntax of MySQL. 

I hope this helps

**Comment by ardichoke** [comment]
I did actually figure it out, though I missed the help page. I ended up looking at the code to work out that it was using a MySQL `LIKE` and not PCRE.

**Comment by gadamo** [comment]
Closing this, after merge #41
