### ISSUE TITLE
Bulk Resolve Hosts Does Nothing

### ISSUE THREAD

**Issue by ardichoke** [echothrust/echofish#35]
Hello, just set up a fresh install on CentOS 6, nginx, php-fpm. I'm just attempting to label my hosts at this point, however on the Manage Hosts page, when I click Resolve Hosts and confirm I want to replace all entries with their DNS values, it does not actually update any of the hosts. If I go into each host individually and use resolve host on it, it does work as expected. I'm not getting any errors in the nginx or php-fpm logs when running the bulk resolve, nor am I getting anything in the access log, suggesting no request is even being sent to the server.

**Comment by proditis** [comment]
Hi there,

What version of echofish are you using? 

If you are using v0.4.x release, could you please checkout the latest master branch and try again?

**Comment by ardichoke** [comment]
Sorry, I should have specified that. I am using the latest code checked out from the master branch. I ended up going through and resolving each host one by one. Fortunately my environment is only a bit over 20 hosts right now. In the process of doing this, I discovered that if a host's lowest level subdomain matches that of another host, it will not update the host's data from DNS.

A practical example, in case it is not clear what I mean. I have two hosts, www.domain.local and www.test.domain.local. When I resolved the first of these two, it worked fine. When I went to resolve the second one, it silently did nothing, I suspect because it tried to set the short name to www, which was already the value for the other host causing it to silently fail.

Perhaps this type of collision and silent failure is also causing the bulk resolve to silently fail?

**Comment by proditis** [comment]
Thanks for clarifying, will try to reproduce your problem and see what fails.

I will keep you posted.

**Comment by proditis** [comment]
I've spotted the bug(s), I'm working on a fix will let you know as soon as its ready.

**Comment by proditis** [comment]
Hi, i've managed to minimize the fix into the following MySQL command. 
```
DROP INDEX `short` ON `host`;
```

Can you give it a try and see if this resolves your problem?

**Comment by ardichoke** [comment]
Confirmed. This fixed both problems.

**Comment by proditis** [comment]
Great, closing this one then.

Thanks for taking the time to report this.
