### ISSUE TITLE
MariaDB PCRE Support

### ISSUE THREAD

**Issue by ardichoke** [echothrust/echofish#36]
Unfortunately, the mysqludf_preg library causes MariaDB v10+ to crash, and there has been no maintenance done on that library in years, suggesting it will not be fixed. Building the library is also becoming more difficult no newer systems due to lack of documentation. The good news is MariaDB 10 has decent built-in PCRE support out of the box (https://mariadb.com/kb/en/mariadb/pcre/), and it seems to be significantly more efficient than the udf_preg library. It would be nice if you could ship a version of the functions which made use of MariaDB's built-in support for those that prefer to use it.

I've already adapted the IP address matching regex, as that one was quite easy. Just needed to change the two relevant lines to this.

`SET ipaddr=(SELECT REGEXP_SUBSTR( msg, '/(([0-9]+)(?:\.[0-9]+){3})/' ));
`

I'm not sure how to approach the abuser regexes though, as they rely on udf_preg's  ability to specify a capture-group which is not present in MariaDB's functionality as far as I can tell.

**Comment by proditis** [comment]
The move to mariadb seems to be the right direction indeed, however this would create a huge load of work for us, we would have to maintain a lot of alternate SQL versions for those who run mariadb >= v10.0.5 and those who don't, while at the same time try to keep compatible with the existing lib_mysqludf_preg for those who use MySQL. 

However if you are willing to undertake this task, we will be more than happy to merge and help out :)

PS: There seems to be way around the capture groups from what i've read.

**Comment by ardichoke** [comment]
Actually, it is working quite well for me after only changing the 5 instances of PREG_CAPTURE in the procedures. I haven't had to modify any other SQL thusfar and I haven't noticed anything SQL related not working as expected. Obviously the capture groups isn't working as I replaces PREG_CAPTURE with a simple REGEXP_SUBSTR, but even that is working well enough for my purposes.

If you could point me in the direction of what you've seen to work around capture groups, I would be happy to integrate that and submit a pull reqest with a MariaDB 10.0.5+ version of the procedures schema.

**Comment by proditis** [comment]
Thats great news :)

I have to make sure that i understood the docs correctly, but it seems that we dont have to define the number of the capture group. We might be able to utilize the non-capturing-groups https://mariadb.com/kb/en/mariadb/pcre/#non-capturing-groups as part of the expressions? 

I hope this makes sense.

**Comment by ardichoke** [comment]
I'm making an attempt to rewrite this, though my mysql skills are not very strong. Getting the grouping value to work shouldn't be hard at all just using REGEXP_REPLACE. Probably don't even need to mess around with non-capturing groups to do that part (and besides, those would need to be in the regex itself, which is supplied by the user).

The tricky part is getting the "occurrence" functionality to work. I don't see an obvious way to replicate occurrence in PCRE, and honestly, I don't really see the point of having it. It seems like if you write your expression properly, you shouldn't have multiple matches for your capture group.

Also, based on a quick search of the codebase, I don't see anywhere that the "extract_ipaddr" procedure is used. Am I missing it, or is this procedure no longer used and just wasn't removed from the schema?

**Comment by proditis** [comment]
I leave this up to you on how you'd like to proceed with the whole capturing, as you seem to be far more experienced with PCRE :)

As for the `occurrence` part this is not being done by the regular expressions. This is a simple counter that gets incremented each time this trigger with that particular "match" gets "fired".  So if you have a trigger that extracts IP's from a message this counter will reflect how many times each of the IP's got matched. This is the `Counter` part from `index.php?r=abuser/incident/admin` for each incident.

Yes `extract_ipaddr` can be safely ignored for now, its being used in some experimental modules we've been working on.

**Comment by ardichoke** [comment]
I don't know that I would call myself very experienced with PCRE, but I do what I can.

The ```occurrence``` that I was referring to is the optional 4th argument to ```PREG_CAPTURE```. The variable being passed to this is actually ```Ccapture``` looking at the procedure. From the ```udf_preg``` documentation:

> ```PREG_CAPTURE(pattern, subject [, capture-group] [, occurence] )``` - capture a named or numeric parenthesized subexpression from a pcre pattern. Capture from a specific match of the regex or the first match if occurence not specified.

So, I can't come up with a reasonable way of recreating that 4th variable using the MariaDB PCRE support. In fact, I can't really see a reason that it is being used. Seems like a properly written regex pattern would match what you are looking for only once.

**Comment by proditis** [comment]
Hey there 

This is there to make the support for preg_capture "complete" (eg allow one to fully control the parameters for the execution of the function). 

You are right though in thinking that this is not something you necessarily need. 

I'd suggest you ignore the `preg_capture` specific fields (`grouping` & `capture`) and see if we can achieve the same results with a bit more "complex/complete" regular expressions.

**Comment by proditis** [comment]
Hey @ardichoke,

We have released a new version of echofish with your changes. Your initiative helped in "motivating" us to move entirely to MariaDB, and by the next version we will remove the `lib_mysqludf_preg` dependency.

I'm closing this issue, feel free to report if you experience any other bugs and thanks a lot for your contributions.

**Comment by ardichoke** [comment]
Sounds good.
