### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by ardichoke** [echothrust/echofish#40]
Echofish doesn't handle IPv6 properly at the moment. When IPv6 addresses are used, the resulting host entry has NULL for the ip, and the IPv6 address gets put into the fqdn and short fields. Since v4 is dying a long slow death, it would be nice to have v6 support.

**Comment by ardichoke** [comment]
It looks like, if the plan is to move toward supporting more recent versions MariaDB only anyway, INET_ATON could be replaced with INET6_ATON to bring in IPv6 support. This would require a schema change since INET6_ATON returns binary data, not integer data (alternatively, could convert it to HEX data, which would still require a schema change, but would at least keep from storing binary data in the database).

https://mariadb.com/kb/en/mariadb/inet6_aton/

**Comment by proditis** [comment]
I guess the time has come for Echofish to support IPv6 :)

I think we'll have something ready by the end of this week so hang on tight :)

**Comment by gadamo** [comment]
@ardichoke After switching to support MariaDB for quite some time now, Echofish should be IPv6-safe. Old INET functions have been replaced with INET6 ones, and they have been working right. That said and besides our tests, we have not tested IPv6 functionality on a production IPv6 environment, so any tests from your part would be welcome.

Closing this one, feel free to report particular issues.
