### ISSUE TITLE
Filtering Logs in the UI should be cumulative

### ISSUE THREAD

**Issue by ardichoke** [echothrust/echofish#42]
When viewing the Logs or the Archive, you can click on a field to filter by the value of that field. However, if you want to filter further by another field, you cannot simply click on it, as it will replace the previous filter instead of adding to it. When doing this type of filtering, it makes more sense to have them be cumulative, with each click of a field adding a filter condition instead of replacing the current filter.

**Comment by proditis** [comment]
The idea for it was to be able to work in similar way as you describe. 

However, we did gave it a go at the early stages of development, but soon the code became a bit too complicated with various silly checks and url generations for each "link". We felt that this was a feature better suited to be implemented through javascript. So we opted for the less complicated solution.

If you have an idea of how we can approach this i'd be more than happy to give it another go.

**Comment by gadamo** [comment]
@ardichoke merge #61 by @proditis addresses cumulative filters when clicking field links. To add a filter without resetting (previously applied) filtering, a user can Shift+click on the links. Simply clicking on the links (without Shift pressed) will still reset any (previously applied) filtering, in favour of the new filter.

**Comment by Artanicus** [comment]
Shift+click at least in Chrome will open a link in a new tab so I can't really say if it's working or not.

**Comment by gadamo** [comment]
@Artanicus What is your browser environment/OS? Our shift+click tests on Chrome and Firefox, both on Linux and Windows, have worked as expected.

**Comment by ardichoke** [comment]
Works fine for me as well... This may be a silly question, but have you pulled in the latest commits from the master branch @Artanicus? You're not on a tagged release?

**Comment by Artanicus** [comment]
Not sure what was wrong, updated to master again and now it's working fine. Seems to be working great even!
