### ISSUE TITLE
 Add column "hostname"

### ISSUE THREAD

**Issue by Koubiacz** [echothrust/echofish#44]
Hello,

Is it possible to add in "Home/syslog /logs" a column named "Hostname" ?
How do I do it?
I have attached an example file.

Thanks
![sample](https://cloud.githubusercontent.com/assets/5717132/17515859/3b6072de-5e3b-11e6-82e2-7653192e69a8.PNG)

**Comment by proditis** [comment]
Hi Koubiacz,

This is definitely something that it can be done. However, we are in the middle of a very big project and the our time is really limited. 

If you don't mind waiting for a while, I'm sure we will manage to find time to implement it in a week or two.

Thanks

Pantelis

**Comment by Koubiacz** [comment]
Thank you for your reply.

Yes it is possible to wait a week or two.
It is already possible to view the host name of the machine leaving the mouse pointer on the ip.
The column will just see faster the hostname

Best regards

**Comment by Artanicus** [comment]
Any update on this feature request? My own personal preference would be to have the Host IP & Host columns combined into one smart column. i.e. if there's a short name defined, show shortname (mouse-over IP), if not defined then display IP.

**Comment by gadamo** [comment]
@Artanicus @Koubiacz This issue has been addressed by @proditis with merge #58 in the latest master branch. 

The implementation, as described by @Artanicus: "if there's a short name defined, show shortname, if not defined then display IP". The mouse-over now displays all host info ( as `IP/fqdn/shortname`)

**Comment by Artanicus** [comment]
Seems to work beautifully, nice!

**Comment by gadamo** [comment]
Closing this one,

@Koubiacz This solution allows echofish users to specify what is displayed on the Host column, on a per-host basis (by adding a shortname to a host). We opted for this versatile solution, rather than adding a separate column, because it does not duplicate information and consumes less space on screen.
