### ISSUE TITLE
"ack based on filter" doesn't work

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#48]
Steps to reproduce with current HEAD:
1. enter Syslog/Logs Msg filter that will match something, for example 'eth0'
2. observe results
3. press "ack based on filt" checkmark
4. observe results

Expected results:
entries with 'eth0' are ACK'd and not visible anymore
Actual results:
entries that matched the filter have not been ACK'd and are still visible

Doing a search, clicking select all and doing a mass acknowledge works fine.

**Comment by gadamo** [comment]
@Artanicus This is now fixed, thank you for reporting. Checkout the latest master and let us know.

**Comment by Artanicus** [comment]
LGTM, fixed.
