### ISSUE TITLE
FR: Stream view

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#49]
When troubleshooting an issue it would be nice to be able to set a filter and watch the messages come in (near) real time. i.e. have an open socket and get pushed new messages matching the filter as they come.

**Comment by gadamo** [comment]
@Artanicus In merge #59 by @proditis we have a (yet unpolished) solution to this issue. Syslog view now updates the gridview on a (hardcoded) time interval. Once you click on the page, the updates stop happening.

Please test this also with the latest master and let us know.

**Comment by Artanicus** [comment]
Sounds like it's either seamless enough to be very intuitive, or odd enough that it will cause confusion. Will need to try it out for a while to say how well it works. Thanks for the progress!

**Comment by gadamo** [comment]
@Artanicus merge #61 by @proditis includes a button to toggle live feed on syslog, in an effort to improve intuitiveness. The same merge adds a new feature for cumulative filtering (user can now Shift+click on links to add filters cumulatively).

**Comment by Artanicus** [comment]
Yeah, that makes it much more clear how it works. I think we can consider this one done!
