### ISSUE TITLE
php7: Resolving single host works, resolving all does not

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#52]
Continuation of #46 since this is very much php7 specific.

Now resolving a single host works fine even on php7 but it seems there's some similar call left that php7 doesn't like. Trying to resolve all hosts results in the same error as before:
Error 500
Only variables should be passed by reference

For the life of me I can't seem to get a stack trace out of yii so I'll leave the details to the experts.

This is on:
- mysql Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- PHP 7.0.13-0ubuntu0.16.04.1
- Ubuntu 16.04

**Comment by gadamo** [comment]
@Artanicus You can pull the latest master for the fix. Fix #51 was partial (fix was only implemented for ip2host resolution, but not host2ip), you should be ok now.

Note: Stack trace can be acquired from `/tmp/application.log`, when you set `YII_DEBUG` to `true`  in `htdocs/index.php`

**Comment by Artanicus** [comment]
LGTM, works now. Found a new issue (again, I break things apparently) but will report that separately.
