### ISSUE TITLE
INSTALL.md needs php dependencies section

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#60]
Upon pulling master now Echofish wouldn't work before I installed php-mbstring. Might be worth adding a PHP dependencies section since mbstring isn't part of at least the Ubuntu default php install.

**Comment by gadamo** [comment]
This will be added in the updated documentation (already being preparing). Thanks for noticing!

**Comment by gadamo** [comment]
@Artanicus Merged #62 that also includes the reference to mbstring requirement in INSTALL.md.
