### ISSUE TITLE
URL param filtering by host fails

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#63]
Clicking Host column link results in URL examples:
index.php?r=syslog/archive/admin&Syslog%5Bhostip%5D=%3D127.0.0.1
index.php?r=syslog/archive/admin&Syslog%5Bhostip%5D=%3D10.0.3.77

Which decodes to something like:
Syslog[hostip]==127.0.0.1

Perhaps with the recent changes hostip is not a valid column anymore?

**Comment by gadamo** [comment]
@Artanicus Oops, this one was a bad copy paste, introduced during recent changes for #44 

While looking into this issue, we fixed another bug where mass-acknowledge with a host filter didn't work. Both fixes are now merged on latest master.

**Comment by Artanicus** [comment]
Working well now, thanks!
