### ISSUE TITLE
FR: Disable / ask for confirmation for filterless filter based ACK

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#64]
If no filters are applied one can click on "Acknowledge filtered" accidentally and clear the entire queue with no way to revert.

I believe it would be a reasonable fail-safe to either disallow filter based ACK if no filters are defined, or to ask for confirmation "Are you sure you want to ACK everything?"

**Comment by gadamo** [comment]
@Artanicus Merge #66 by @proditis adds a confirmation dialogue "Are you sure you want to acknowledge with empty filters?". After updating to the latest master, click with no hesitation.

**Comment by Artanicus** [comment]
Works nice, thanks!
