### ISSUE TITLE
multi filter ACK fails

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#69]
If I shift-click select multiple filters and then select filter based acknowledge, no lines are ACKd. Having only one filter allows the ACK to succeed. For testing I used Facility and Host. ACK both with only Facility or Host works fine.

**Comment by gadamo** [comment]
Merge #71 addresses this issue. Please pull the latest master to test and let us know.

Thank you for reporting this.

**Comment by gadamo** [comment]
@Artanicus Merge #71 addresses this issue. Please pull the latest master to test and let us know.

Thank you for reporting this.

Because of subtle changes in schema/echofish-events.sql, is is advised to re-import this file to keep in sync with master.

**Comment by paran0ids0ul** [comment]
After installing the latest master, I successed in multi-filtering ACK both host - facility, host - level and facility - level. Great work guys.

**Comment by gadamo** [comment]
@paran0ids0ul @Artanicus Closing this one.
