### ISSUE TITLE
IPV6 Support Breaks Abuser Reporting

### ISSUE THREAD

**Issue by ardichoke** [echothrust/echofish#73]
The abuser parser function is using INET6_ATON to convert IPs for storage. This is all well and good, however, the database schema for abuser_incident table has the ip field as an int(10) unsigned (originally), which is not compatible with the output of INET6_ATON, which returns VARBINARY(4) or VARBINARY(16) depending on the address type. There needs to be a schema conversion for anyone upgrading.

https://mariadb.com/kb/en/mariadb/inet6_aton/

I was able to fix this by converting the ip column to VARBINARY(16) and then converting any preexisting values by running them through INET6_ATON(INET_NTOA(ip))

(Sorry for all the edits, as I was fixing this on my own install, I realized my original report wasn't entirely accurate)

**Comment by gadamo** [comment]
With the creation of schema/updates/v0.5-to-v0.6.sql on master, this change is now included.

@ardichoke Thank you for reporting this!
