### ISSUE TITLE
blackhole plugin dependency needs to be more discoverable

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#77]
I just spent several hours scratching my head why I'm not getting any more log entries. Turns out a MariaDB upgrade (Ubuntu 17.04-beta2) now got me to a version where ha_blackhole.so needs to be specifically loaded. Easy to fix once you know what the issue is! :-)

It would be nice if this error condition could be somehow surfaced in the UI so that it's clear your current setup won't function.

**Comment by gadamo** [comment]
@Artanicus Thank you for the concise report. We could make sure the Blackhole engine will always be available by adjusting my.cnf:

```
[mysqld]
plugin-load=BLACKHOLE=ha_blackhole.so
blackhole=FORCE
```

Hope this helps.

@proditis I have tested this on OpenBSD/Debian/CentOS, so I am also adding it on INSTALL.md with #78 (when merged, the guides in contrib/ can follow).

**Comment by Artanicus** [comment]
Sounds great.

In the long run it might be beneficial to do some basic sanity checking in the web UI and pop up the error bar if critical features are found to be disabled. Someone is bound to miss some parts of the installation documents.

**Comment by gadamo** [comment]
After #81 was merged, the instructions are also included in contributed recipes for setting up echofish on the different OS and userland tools combinations.
