### ISSUE TITLE
(via email) Fresh install; not getting any log entries

### ISSUE THREAD

**Issue by gadamo** [echothrust/echofish#79]
Received this one via e-mail, opening this issue to better communicate and keep track of the resolution.

```
Hello,

I installed Echofish on an Ubuntu 16.04 server with Apache, MySQL and PHP 7.1. The install
ran smoothly and I can access the web interface without problem, no error message.

The issue is that I do not see any log entry anywhere in the application.  I checked the 
"Manage Syslog Messages" page, enabled / disabled the "Toggle live feed" button but it 
doesn't make any difference, nothing shows.

Any advice?

Thank you.
```

**Comment by Artanicus** [comment]
At least issue #77 might cause & fix this, newest versions of MariaDB do not have the blackhole plugin enabled by default anymore resulting in everything looking really good except no logs are ever received.

**Comment by gadamo** [comment]
I will try to list an initial verification process for this installation, based on the information provided:

1. Connect to mysql using the cli and run `SHOW ENGINES;` to verify that BLACKHOLE engine is loaded
2. If BLACKHOLE is loaded fine, try to insert a sample log, e.g. `INSERT INTO archive_bh (host, facility, priority, level, received_ts, program, msg,pid,tag) VALUES ( '10.20.11.22', '10', '5','5', NOW(), 'sudo', 'testing','1234', 'sudo:' );`

Notes:

* If blackhole is not enabled in your setup, follow instructions from issue #77.
* If you get warnings after Step 2, please run `SHOW WARNINGS` and let us know.
* If the new entry appears on the web-ui, you are indeed missing the syslog part, but i would need to peek at your syslog daemon's config to assist further.

**Comment by NQuebec** [comment]
Thank you for the help George, see below:

BLACKHOLE is loaded, see the output of SHOW ENGINES;
| Engine             | Support | Comment                                                        | Transactions | XA   | Savepoints |
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
| BLACKHOLE          | YES     | /dev/null storage engine (anything you write to it disappears) | NO           | NO   | NO         

The MySQL INSERT worked fine too and Echofish shows it on the Syslog page (this is the only record shown).

Let me know what next.  Thanks again.

**Comment by gadamo** [comment]
@NQuebec Have you configured a syslog server to forward logs to mysql, as described in the guides? Do you use syslog-ng or rsyslog? Can you please share the relevant sections of your syslog server's configuration?

**Comment by NQuebec** [comment]
Actually no, sorry, I thought Echofish was reading the log files directly and importing into MySQL.

Do you have any recommendation syslog-ng vs rsyslog?

thank you.

**Comment by gadamo** [comment]
We have guides for both. Our platfrom of choice has always been OpenBSD with syslog-ng. That said, plenty of people run echofish on either, and rsyslog has gained a lot of traction lately. I think your Linux distro already ships with rsyslog, so it would make sense to configure that one before trying alternatives.

I would go for a setup similar to [centos-rsyslog-mysql](https://github.com/echothrust/echofish/blob/master/contrib/Echofish-CentOS7-rsyslog.md#rsyslog-mysql), which is based on the generic [recipe for rsyslog](https://github.com/echothrust/echofish/blob/master/contrib/rsyslog-echofish.conf).

You may also want to peek at this [merge request pending aproval](https://github.com/echothrust/echofish/pull/83/files) for a guide on Ubuntu 16.04, which is yet to-be-tested but may help since it's on your actual platform.

Let me know how this goes.

**Comment by gadamo** [comment]
@NQuebec check the [Ubuntu Guide](https://github.com/echothrust/echofish/blob/master/contrib/Echofish-Ubuntu-16.04-rsyslog.md#rsyslog-mysql) which was merged today.

Having installed `rsyslog-mysql` package, simply remove file `mysql.conf` and create `echofish.conf` in `/etc/rsyslog.d/` and restart `rsyslog.service`, as shown in the guide.

**Comment by NQuebec** [comment]
Excellent guide, thank you!

Everything works fine now, thanks for the help and the great product!

N.
