### ISSUE TITLE
Whitelist Export error 500

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#82]
2017/04/10 13:11:52 [error] [php] include(SimpleXMLElement.php): failed to open stream: No such file or directory (/var/www/yii/framework/yiilite.php:247)
Stack trace:
#0 /var/www/html/protected/modules/lists/controllers/WhiteController.php(282): spl_autoload_call()
#1 /var/www/yii/framework/yiilite.php(4139): WhiteController->actionExport()
#2 /var/www/yii/framework/yiilite.php(3652): CInlineAction->runWithParams()
#3 /var/www/yii/framework/yiilite.php(6895): WhiteController->runAction()
#4 /var/www/yii/framework/yiilite.php(6904): CFilterChain->run()
#5 /var/www/yii/framework/yiilite.php(4030): CAccessControlFilter->filter()
#6 /var/www/yii/framework/yiilite.php(6937): WhiteController->filterAccessControl()
#7 /var/www/yii/framework/yiilite.php(6892): CInlineFilter->filter()
#8 /var/www/yii/framework/yiilite.php(3642): CFilterChain->run()
#9 /var/www/yii/framework/yiilite.php(3627): WhiteController->runActionWithFilters()
#10 /var/www/yii/framework/yiilite.php(1761): WhiteController->run()
#11 /var/www/yii/framework/yiilite.php(1681): CWebApplication->runController()
#12 /var/www/yii/framework/yiilite.php(1202): CWebApplication->processRequest()
#13 /var/www/html/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=lists/white/export

The file SimpleXMLElement.php is nowhere on my system, forgotten dependency?

**Comment by gadamo** [comment]
IIRC you run Ubuntu 16.04, so you should install `php7.0-xml` package. After restarting FPM service, you should be good. There is no official or contributed guide for Ubuntu (any takers? wink-wink), so we can just keep this in mind for the future.

**Comment by Artanicus** [comment]
That did it. I did check packages.ubuntu.com but for some reason it didn't catch that it should've been from a package.

I'll start looking at writing up a Ubuntu guide, I think I've hit most of the possible pitfalls. :-)
