### ISSUE TITLE
This sql wrong how to solve

### ISSUE THREAD

**Issue by dragon-D** [echothrust/echofish#85]
I see syslog suggested error 1305 FUNCTION ETS_echofish.inet6_ntoa does not exist. The SQL statement was was: SELECT t. *, Inet6_ntoa (host.ip) as hostip FROM `syslog` `t` LE Will this inet6_ntoa function how come

**Comment by gadamo** [comment]
@dragon-D Seems like you are trying to run echofish on mysql or an older version of mariadb that does not have the IPv6 functionality we require. 

Echofish backend is developed on MariaDB 10.0.25 (and works fine on other reasonably recent versions too). Strictly speaking, we should run fine on MariaDB versions higher than 10.0.5 (due to PCRE pattern matching).

**Comment by dragon-D** [comment]
@gadamo    I upgraded MariaDB to 10 or more can really, and very grateful

**Comment by gadamo** [comment]
@dragon-D Glad it worked out well, closing this issue.

**Comment by dragon-D** [comment]
@gadamo If you want to support the mysql5 version of echofish, how should change it?

**Comment by dragon-D** [comment]
I would like to write mysql here rsyslog change, rsyslog error 
```
rsyslogd: db error (1305): FUNCTION ETS_echofish.INET6_ATON does not exist
```
My rsyslog configuration
···
#Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

#Provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 514

#sql + rules for rsyslog integration with Echofish
#Load rsyslog MySQL plugin
$ModLoad ommysql.so

#Generic template
$template dbFormat,"INSERT INTO archive_bh (host, facility, priority, level, received_ts, program, msg,tag) VALUES ( '%fromhost-ip%', '%syslogfacility%', '%syslogpriority%','%syslogseverity%', '%timereported:::date-mysql%', TRIM('%programname%'), TRIM('%msg%'), '%syslogtag%' )",SQL

*.* :ommysql:127.0.0.1,ETS_echofish,*****@,*****@sql678;dbFormat
···

**Comment by dragon-D** [comment]
Just read the next sql to find the problem, has been resolved

**Comment by gadamo** [comment]
@dragon-D Sorry but I can't figure out exactly what you're saying. Can you please state clearly if your problem has been resolved? Otherwise please try to describe your issue again with more emphasis on the problem.

**Comment by gadamo** [comment]
Closing this one due to inactivity, please consider issuing a new (descriptive) ticket if your problem persists.
