### ISSUE TITLE
ERROR 1242 (21000): Subquery returns more than 1 row

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#95]
```
MariaDB [ETS_echofish]> INSERT INTO archive_bh (host, facility, priority, level, received_ts, program, msg,pid,tag) VALUES ('pound', '3', '6','6', '20190303145102', 'tester', 'foobar', '-', 'pound');
ERROR 1242 (21000): Subquery returns more than 1 row
```

This started happening only recently (~3 days ago) but several weeks after the latest mariadb upgrade (2019-02-08).

```
%> mariadb --version
mariadb  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
%> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

Any idea what's broken? I don't see there being a subquery in the insert itself so it must be something with the triggers?

**Comment by Artanicus** [comment]
Dug into the triggers and it was caused by a duplicate host entry for the host 'pound' .. it had ended up in the list with two hostnames, pound and pound.lxc. Probably happened when I ran a "resolve all hosts". Looks like I've got some manual deduping to do!

Any way this could be prevented? Duplicate hosts seem to cause bad issues but detecting it is left to the admin and fixing is very manual.

**Comment by proditis** [comment]
Hi there,

Can you provide the SELECT current output of the duplicate hosts and if possible before the resolve also? This will help a lot in order to figure out which part of the resolve process causes this issue.

Best regards,

Pantelis

**Comment by Artanicus** [comment]
Unfortunately I didn't grab the data when it happened since I had to fix it quickly. Will post a new bug if the issue repeats.
