### ISSUE TITLE
[FR] Allow longer hostnames in whitelists

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#97]
With the improved support for hostname based matching I've run into a limitation of the whitelist entries being limited to a hostname of 20 characters. This limit is easily exceeded when fqdn's are used, such as: gateway.corp.example.com.

The error given is: "Host is too long (maximum is 20 characters)."

Now what I can do is add say "gateway.corp.%" but this gets annoying when creating a lot of whitelist entries from historical data since the field is pre-filled to the fqdn.

**Comment by proditis** [comment]
Hi @Artanicus 

Nice catch. Increased the max from 20 to 40 which is also the size defined within the schema. This should fix the issue you're having for now. 

In the future I will increase the size further, but i don't want go into schema changes at the moment, so i hope this is sufficient for now.

Let me know if that fixes your issue.

**Comment by Artanicus** [comment]
Working great, thanks!
